### ISSUE TITLE
Identify what versions of Jackson work with out current implementations and if any changes can be made to support more versions

### ISSUE THREAD

**Issue by jcksndfrd** [jcksndfrd/azure-sdk-for-java#18]

**Comment by ajpetherick** [comment]
Jackson 2.1.x through to the latest version of 2.13.4 all passed unit tests without any condition logic regarding the version. 
2.0.x failed with a NoSuchMethodException as it couldn't find the createGenerator from the JsonFactory class reflectively. 
JacksonJsonWriter test results are attached. 
[JacksonJsonWriter test results.docx](https://github.com/jcksndfrd/azure-sdk-for-java/files/9587105/JacksonJsonWriter.test.results.docx)

**Comment by 20004427** [comment]
For JacksonReader. The current implementation works for 2.8.0 onwards. 
2.7.9 throws a NoSuchMethodException - the method CurrentToken does not exist. 
I tested back to 2.6.7 
2.6.7 - 2.7.9 all throw the error above.
2.3.1 also throws the same error. 
I've attached the results below


[JacksonJsonReader test results.docx](https://github.com/jcksndfrd/azure-sdk-for-java/files/9593226/JacksonJsonReader.test.results.docx)

**Comment by 20004427** [comment]
It looks like the method handle just needs to be changed to GetCurrentToken in versions prior to 2.8
CurrentToken is added in 2.8 and GetCurrentToken is removed in 2.9
2.8:
https://github.com/FasterXML/jackson-core/blob/6ea4f42550a1f19f4ded2629a909747cb90423c0/src/main/java/com/fasterxml/jackson/core/JsonParser.java#L840
2.7:
https://github.com/FasterXML/jackson-core/blob/b8563da2b5d4259379b957cda7544da968be84db/src/main/java/com/fasterxml/jackson/core/JsonParser.java#L767

**Comment by jcksndfrd** [comment]
Currently both `JacksonJsonReader` and `JacksonJsonWriter` support Jackson versions 2.9.4 and upwards
